// src/components/Timer.vue
<template>
  <div class="card p-6 w-full max-w-sm mx-auto bg-white shadow-lg animate-fade">
    <div class="flex flex-col items-center space-y-4">
      <Eye class="w-12 h-12 text-primary" />
      <h2 class="text-2xl font-semibold text-gray-800">Screen Time Timer</h2>
      <div class="text-4xl font-bold text-primary">{{ formattedTime }}</div>
      <div class="flex gap-2 w-full">
        <button 
          @click="toggleTimer"
          class="flex-1 flex items-center justify-center space-x-2 bg-primary text-white px-4 py-2 rounded hover:bg-primary/90"
        >
          <component :is="isActive ? PauseCircle : PlayCircle" class="w-5 h-5" />
          <span>{{ isActive ? 'Stop' : 'Start' }}</span>
        </button>
        <button 
          @click="resetTimer"
          class="flex items-center justify-center space-x-2 border border-input bg-background hover:bg-accent px-4 py-2 rounded"
        >
          <RotateCcw class="w-5 h-5" />
          <span>Reset</span>
        </button>
      </div>
    </div>
  </div>

  <!-- Dialog -->
  <Teleport to="body">
    <div v-if="showDialog" class="fixed inset-0 bg-black/50 flex items-center justify-center z-50">
      <div class="bg-white p-6 rounded-lg max-w-md w-full mx-4">
        <h2 class="text-xl font-semibold mb-4">Timer Started! 👁️</h2>
        <p class="text-gray-600 mb-6">Your eyes will be monitored for the next 20 minutes</p>
        <div class="flex justify-center p-6">
          <div class="relative w-32 h-32">
            <div 
              class="absolute w-32 h-32 rounded-full transition-colors duration-1000"
              :style="{
                background: seconds % 1200 === 0 ? 'red' : 'white',
                border: '4px solid #666'
              }"
            >
              <div 
                class="absolute top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2 w-16 h-16 rounded-full transition-colors duration-1000"
                :style="{
                  background: seconds % 1200 === 0 ? '#ff3333' : '#333'
                }"
              >
                <div 
                  class="absolute top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2 w-8 h-8 rounded-full transition-colors duration-1000"
                  :style="{
                    background: seconds % 1200 === 0 ? '#ff0000' : '#000'
                  }"
                />
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </Teleport>
</template>

<script setup lang="ts">
import { ref, onUnmounted, computed } from 'vue'
import { Eye, PauseCircle, PlayCircle, RotateCcw } from 'lucide-vue-next'

const seconds = ref(0)
const isActive = ref(false)
const showDialog = ref(false)

const formattedTime = computed(() => {
  const hours = Math.floor(seconds.value / 3600)
  const minutes = Math.floor((seconds.value % 3600) / 60)
  const secs = seconds.value % 60
  return `${hours.toString().padStart(2, '0')}:${minutes.toString().padStart(2, '0')}:${secs.toString().padStart(2, '0')}`
})

let intervalId: number | null = null

const toggleTimer = () => {
  if (!isActive.value) {
    showDialog.value = true
  }
  isActive.value = !isActive.value

  if (isActive.value) {
    intervalId = setInterval(() => {
      seconds.value++
      if (seconds.value % 1200 === 0) {
        alert('Time for an Eye Break! 👀\nLook at something 20 feet away for 20 seconds')
      }
    }, 1000)
  } else if (intervalId) {
    clearInterval(intervalId)
  }
}

const resetTimer = () => {
  if (intervalId) {
    clearInterval(intervalId)
  }
  isActive.value = false
  seconds.value = 0
  showDialog.value = false
}

onUnmounted(() => {
  if (intervalId) {
    clearInterval(intervalId)
  }
})
</script>

<style scoped>
.card {
  transition: all 0.3s ease;
}
</style>

// src/components/Timer.tsx
import { useState, useEffect } from 'react';
import { useToast } from "@/components/ui/use-toast";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Eye, PauseCircle, PlayCircle, RotateCcw } from "lucide-react";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";

const Timer = () => {
  const [seconds, setSeconds] = useState(0);
  const [isActive, setIsActive] = useState(false);
  const [showDialog, setShowDialog] = useState(false);
  const { toast } = useToast();

  useEffect(() => {
    let intervalId: ReturnType<typeof setInterval>;

    if (isActive) {
      intervalId = setInterval(() => {
        setSeconds(prevSeconds => {
          const newSeconds = prevSeconds + 1;
          if (newSeconds % 1200 === 0) {
            toast({
              title: "Time for an Eye Break! 👀",
              description: "Look at something 20 feet away for 20 seconds",
              duration: 20000,
            });
          }
          return newSeconds;
        });
      }, 1000);
    }

    return () => clearInterval(intervalId);
  }, [isActive, toast]);

  const toggleTimer = () => {
    if (!isActive) {
      setShowDialog(true);
    }
    setIsActive(!isActive);
  };

  const resetTimer = () => {
    setIsActive(false);
    setSeconds(0);
    setShowDialog(false);
  };

  const formatTime = (totalSeconds: number) => {
    const hours = Math.floor(totalSeconds / 3600);
    const minutes = Math.floor((totalSeconds % 3600) / 60);
    const secs = totalSeconds % 60;
    return `${hours.toString().padStart(2, '0')}:${minutes.toString().padStart(2, '0')}:${secs.toString().padStart(2, '0')}`;
  };

  return (
    <>
      <Card className="p-6 w-full max-w-sm mx-auto bg-white shadow-lg animate-fade">
        <div className="flex flex-col items-center space-y-4">
          <Eye className="w-12 h-12 text-primary" />
          <h2 className="text-2xl font-semibold text-gray-800">Screen Time Timer</h2>
          <div className="text-4xl font-bold text-primary">{formatTime(seconds)}</div>
          <div className="flex gap-2 w-full">
            <Button 
              onClick={toggleTimer}
              className="flex-1 flex items-center justify-center space-x-2"
            >
              {isActive ? (
                <>
                  <PauseCircle className="w-5 h-5" />
                  <span>Stop</span>
                </>
              ) : (
                <>
                  <PlayCircle className="w-5 h-5" />
                  <span>Start</span>
                </>
              )}
            </Button>
            <Button 
              onClick={resetTimer}
              variant="outline"
              className="flex items-center justify-center space-x-2"
            >
              <RotateCcw className="w-5 h-5" />
              <span>Reset</span>
            </Button>
          </div>
        </div>
      </Card>

      <Dialog open={showDialog} onOpenChange={setShowDialog}>
        <DialogContent className="sm:max-w-md">
          <DialogHeader>
            <DialogTitle>Timer Started! 👁️</DialogTitle>
            <DialogDescription>
              Your eyes will be monitored for the next 20 minutes
            </DialogDescription>
          </DialogHeader>
          <div className="flex justify-center p-6">
            <div className="relative w-32 h-32">
              <div 
                className="absolute w-32 h-32 rounded-full"
                style={{
                  background: seconds % 1200 === 0 ? 'red' : 'white',
                  border: '4px solid #666',
                  transition: 'background-color 1s ease-in-out',
                }}
              >
                <div 
                  className="absolute top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2 w-16 h-16 rounded-full"
                  style={{
                    background: seconds % 1200 === 0 ? '#ff3333' : '#333',
                    transition: 'background-color 1s ease-in-out',
                  }}
                >
                  <div 
                    className="absolute top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2 w-8 h-8 rounded-full"
                    style={{
                      background: seconds % 1200 === 0 ? '#ff0000' : '#000',
                      transition: 'background-color 1s ease-in-out',
                    }}
                  />
                </div>
              </div>
            </div>
          </div>
        </DialogContent>
      </Dialog>
    </>
  );
};

export default Timer;
